version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/seed
      - persist_to_workspace:
        root: .
        paths:
          - .
workflows:
  node-tests:
    jobs:
      - node/test
