version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    # Get the latest version of mongo and node
    docker:
      - image: 'circleci/node:latest'
      - image: 'circleci/mongo:latest'
    steps:
      # Get the latest version of NPM
      - checkout
      # Install dependencies
      - run: npm install
      # Seed mongoDB
      - run: npm run seed
      # Run tests
      - run: npm run test
