version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
      - image: 'circleci/mongo:latest'
    steps:
      - checkout
      - run: npm install
      - run: npm run seed
      - run: npm run test
